### GENERAL SETTINGS ###
highlighter: pygments

# Site settings
title: Random snippets of knowledge
description: "Random snippets of knowledge"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://neutmute.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#22A7F0" 
  primary_rgb: #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Random snippets of knowledge"
